### PR TITLE
Update tank app

### PR DESCRIPTION
**Pull request by EvaKaul**
- automatic start of filling process
- automatic value generation for 'faulty bottles'
- embedded program alarm for testing

### CODE REVIEW

**Comment by EvaKaul** [comment]
Hi @vasilogi, could you please review my GitHub changes regarding the tank application, too? There are only minor changes (small changes in docu, new TIA project)... Thanks a lot!

**Review by vasilogi — APPROVED** [review]
Hi Eva! It looks totally fine to me

**Comment by vasilogi** [comment]
Hi @EvaKaul, the changes look fine to me. I just approved them 👍

**Comment by vasilogi** [comment]
@Ioatina please consider to merge 💯

**Pull request merged**
