### PR TITLE
Update tank application

### PR DESCRIPTION
**Pull request by EvaKaul**
- Updated Readme
    - new section "Operation of PLC" (see issue)
    - added new use case
- Updated TIA project
    - updated HMI + bugfixes
    - new datatype for "process" parameters
    - added overflow handling for parameter numberProduced

### CODE REVIEW

**Comment by EvaKaul** [comment]
Please check, if this version resolves the issue #9

**Review by HummelN7872 — APPROVED** [review]
Appoved

**Comment by EndyCZ** [comment]
1.  In [overview](https://github.com/industrial-edge/miscellaneous/tree/update-tank-application/tank%20application#overview) industrial edge shoul have capital letters
2. Is it STEP 7 TIA project or just TIA Project? here https://github.com/industrial-edge/miscellaneous/blame/update-tank-application/tank%20application/README.md#L37
3. Is it really good idea to describe the Edge use cases and links to other application examples? What if they changes (either link or use case)? Who will maintain this then? This is easy to forget and should be described in the linked how-tos i believe. https://github.com/industrial-edge/miscellaneous/tree/update-tank-application/tank%20application#edge-use-cases 
4. I don't think many people know or use 7z format. I suggest to change the format to zip file. 
5. Another point is that we should probably use git Large File Storage (LFS) extension for Git because we are working with binary files. 

See here how to use https://git-lfs.github.com/
See here for storage limitations (including LFS) https://docs.github.com/en/github/managing-large-files/versioning-large-files/about-storage-and-bandwidth-usage

Otherwise really nice. :)

**Review by EndyCZ — CHANGES_REQUESTED** [review]
1. In overview industrial edge shoul have capital letters
2. Is it STEP 7 TIA project or just TIA Project? here https://github.com/industrial-edge/miscellaneous/blame/update-tank-application/tank%20application/README.md#L37
3. Is it really good idea to describe the Edge use cases and links to other application examples? What if they changes (either link or use case)? Who will maintain this then? This is easy to forget and should be described in the linked how-tos i believe. https://github.com/industrial-edge/miscellaneous/tree/update-tank-application/tank%20application#edge-use-cases
4. I don't think many people know or use 7z format. I suggest to change the format to zip file.
5. Another point is that we should probably use git Large File Storage (LFS) extension for Git because we are working with binary files.

See here how to use https://git-lfs.github.com/
See here for storage limitations (including LFS) https://docs.github.com/en/github/managing-large-files/versioning-large-files/about-storage-and-bandwidth-usage

Otherwise really nice. :)

**Comment by HummelN7872** [comment]
Regarding Ondrejs comments:

> 1. In overview industrial edge shoul have capital letters
- Agree 
> 2. Is it STEP 7 TIA project or just TIA Project? here https://github.com/industrial-edge/miscellaneous/blame/update-tank-application/tank%20application/README.md#L37
- In this case STEP 7 is correct as the STEP 7 part of the TIA Portal is the PLC programming part. But I also do not mind when changing it just to TIA because the rest of the time it is just called TIA project. To be even more precise we should call it TIA **Portal** Project
> 3. Is it really good idea to describe the Edge use cases and links to other application examples? What if they changes (either link or use case)? Who will maintain this then? This is easy to forget and should be described in the linked how-tos i believe. https://github.com/industrial-edge/miscellaneous/tree/update-tank-application/tank%20application#edge-use-cases
- I think it is a good overview and I like it. The description is pretty generic thats way there will not be a big need adapting it frequently
> 4. I don't think many people know or use 7z format. I suggest to change the format to zip file.
> 5. Another point is that we should probably use git Large File Storage (LFS) extension for Git because we are working with binary files.
> See here how to use https://git-lfs.github.com/
> See here for storage limitations (including LFS) https://docs.github.com/en/github/managing-large-files/versioning-large-files/about-storage-and-bandwidth-usage
-  Are there any advantage or even disadvantage for the user downloading the files? Or is it just about the upload of the files?
> 
> Otherwise really nice. :)

**Comment by EvaKaul** [comment]
1. changed everything into "Industrial Edge"
2. changed everything into "TIA Portal project"
3. no changes here - leave everything as it is
4. i also uploaded the project as .zip ... if I now delete the .7z file, all the history is gone... shall I delete it?
5. at the moment i think we have no problems regarding big files, but could be an issue in the futere. I found this description regarding LFS: 

image

**Comment by EndyCZ** [comment]
Yes, I would delete the 7z file. Otherwise look nice. :) You are right on the LFS issue.

**Comment by EvaKaul** [comment]
I deleted the 7z project.
@EndyCZ: your approval is still missing, so that I can do the merge.
But before that maybe we think about the invalid links that refer to the 7z-Project. All HowTos, that refer to that project have to be adapted. How to handle that the best way - each owner by itself or should I change all links?

**Comment by HummelN7872** [comment]
I would suggest create a issue for all affected repositories. I think the links should be adapted and refer to the [miscellaneous/tank application](https://github.com/industrial-edge/miscellaneous/tree/main/tank%20application) folder and not directly to the zip file

**Review by EndyCZ — APPROVED** [review]
Nice :)

**Pull request merged**
