### PR TITLE
Final version of Readme.md for tank application

### PR DESCRIPTION
**Pull request by EvaKaul**
please check if Readme is ok or something is missing

### CODE REVIEW

**Review by HummelN7872 — CHANGES_REQUESTED** [review]
Could you please also enter a short description in the [Main Readme] (https://github.com/industrial-edge/miscellaneous/blob/main/README.md) including a table of content of the avialable folder (right now it would only be the tank application).

**Review by HummelN7872 — CHANGES_REQUESTED** [review]
Please adapt changes like discussed

**Review by HummelN7872 — APPROVED** [review]
Changes accepted

**Comment by EvaKaul** [comment]
finished reviewing process

**Pull request merged**
